core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from home import views as home_views  # Changed import
from wfdash import views as wfdash_views  # Changed import
from django.views.static import serve


handler404 = 'home.views.handler404'
handler403 = 'home.views.handler403'
handler500 = 'home.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),  # Make sure this line exists
    path('', include('home.urls')),
    path("api/", include("apps.api.urls")),
    path('accounts/', include('allauth.urls')),
    path('', include('apps.file_manager.urls')),
    path('tasks/', include('apps.tasks.urls')),
    path('charts/', include('apps.charts.urls')),
    path("tables/", include("apps.tables.urls")),
    path('users/', include('apps.users.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('wfdash/', include('wfdash.urls')),
    path('quotes/', include('quotes.urls')),
    path('orders/', include('orders.urls')),
    path('drivers/', include('driver_list.urls')),
    path('', include('pwa.urls')),
    path('stock/', include('stock_management.urls')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('stock-orders/', include('stock_orders.urls', namespace='stock_orders')),
    path('portal/', include('customer_portal.urls', namespace='customer_portal')),
    path('delivery/', include('delivery_notes.urls', namespace='delivery_notes')),
    path('delivery-notes/', include('delivery_notes.urls', namespace='delivery_notes')),
    path("rep/", include("rep_portal.urls", namespace="rep_portal")),
    path("search/", include("search.urls", namespace="search")),
    
    path('repairs/', include('repairs.urls', namespace='repairs')),

    path(
        "internal_stock/", include("internal_stock.urls", namespace="internal_stock")
    ),  # Add this line




    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    # Debug toolbar
    path("__debug__/", include("debug_toolbar.urls")),
    path('save-subscription/', home_views.save_subscription, name='save_subscription'),
    path('send-test-notification/', home_views.send_test_notification, name='send_test_notification'),
    path('offline/', home_views.offline_view, name='offline'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path('i18n/', home_views.i18n_view, name="i18n_view")  # Correct import for i18n_view
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views
from django.contrib.auth import views as auth_views



def redirect_to_admin(request):
    return redirect('/admin/')



urlpatterns = [
  # Dashboard
  path('', views.default, name='login_v3'),
  path('dashboard/ecommerce/', views.dashboard_ecommerce, name='dashboard_ecommerce'),
  path('dashboard/crm/', views.dashboard_crm, name='dashboard_crm'),
  path('dashboard/analytics/', views.dashboard_analytics, name='dashboard_analytics'),
  path('dashboard/crypto/', views.dashboard_crypto, name='dashboard_crypto'),
  path('dashboard/project/', views.dashboard_project, name='dashboard_project'),


  path('', redirect_to_admin, name='index'),


  # Page Layouts
  path('page-layouts/vertical/static-layout/', views.static_layout, name='static_layout'),
  path('page-layouts/vertical/fixed-layout/', views.fixed_layout, name='fixed_layout'),
  path('page-layouts/vertical/navbar-fixed-layout/', views.navbar_fixed_layout, name='navbar_fixed_layout'),
  path('page-layouts/vertical/collapse-layout/', views.collapse_layout, name='collapse_layout'),

  path('page-layouts/horizontal-layout/', views.horizontal_layout, name='horizontal_layout'),
  path('page-layouts/box-layout/', views.box_layout, name='box_layout'),
  path('page-layouts/rtl-layout/', views.rtl_layout, name='rtl_layout'),
  path('page-layouts/light-layout/', views.light_layout, name='light_layout'),
  path('page-layouts/dark-layout/', views.dark_layout, name='dark_layout'),
  path('page-layouts/color-icon-layout/', views.color_icon_layout, name='color_icon_layout'),

  # Widgets
  path('widget/statistic/', views.widget_statistic, name='widget_statistic'),
  path('widget/data/', views.widget_data, name='widget_data'),
  path('widget/table/', views.widget_table, name='widget_table'),
  path('widget/user-card/', views.widget_user_card, name='widget_user_card'),
  path('widget/chart/', views.widget_chart, name='widget_chart'),

  # User
  path('user/profile/', views.user_profile, name='user_profile'),
  path('user/social-profile/', views.social_profile, name='social_profile'),
  path('user/user-card/', views.user_card, name='user_card'),
  path('user/user-list/', views.user_list, name='user_list'),

  # Basic Components
  path('elements/basic/alert/', views.bc_alert, name='bc_alert'),
  path('elements/basic/button/', views.bc_button, name='bc_button'),
  path('elements/basic/badges/', views.bc_badges, name='bc_badges'),
  path('elements/basic/breadcrumb-pagination/', views.bc_breadcrumb_pagination, name='bc_breadcrumb_pagination'),
  path('elements/basic/cards/', views.bc_card, name='bc_card'),
  path('elements/basic/collapse/', views.bc_collapse, name='bc_collapse'),
  path('elements/basic/carousel/', views.bc_carousel, name='bc_carousel'),
  path('elements/basic/grid-system/', views.bc_grid, name='bc_grid'),
  path('elements/basic/progress/', views.bc_progress, name='bc_progress'),
  path('elements/basic/modal/', views.bc_modal, name='bc_modal'),
  path('elements/basic/spinner/', views.bc_spinner, name='bc_spinner'),
  path('elements/basic/navs-tabs/', views.bc_navs_tabs, name='bc_navs_tabs'),
  path('elements/basic/typography/', views.bc_typography, name='bc_typography'),
  path('elements/basic/tooltips-popover/', views.bc_tooltips_popover, name='bc_tooltips_popover'),
  path('elements/basic/toasts/', views.bc_toast, name='bc_toast'),
  path('elements/basic/extra/', views.bc_extra, name='bc_extra'),

  # Advance Components
  path('elements/advance/alert/', views.ac_alert, name='ac_alert'),
  path('elements/advance/datepicker/', views.ac_datepicker, name='ac_datepicker'),
  path('elements/advance/lightbox/', views.ac_lightbox, name='ac_lightbox'),
  path('elements/advance/modal/', views.ac_modal, name='ac_modal'),
  path('elements/advance/notification/', views.ac_notification, name='ac_notification'),
  path('elements/advance/pnotify/', views.ac_pnotify, name='ac_pnotify'),
  path('elements/advance/range-slider/', views.ac_rangeslider, name='ac_rangeslider'),
  path('elements/advance/slider/', views.ac_slider, name='ac_slider'),
  path('elements/advance/syntax-highlighter/', views.ac_syntax_highlighter, name='ac_syntax_highlighter'),
  path('elements/advance/tour/', views.ac_tour, name='ac_tour'),
  path('elements/advance/treeview/', views.ac_treeview, name='ac_treeview'),

  # Animation
  path('elements/animation/', views.animation, name='animation'),

  # Icons
  path('icons/feather-icon/', views.feather_icon, name='feather_icon'),
  path('icons/font-awesome/', views.font_awesome, name='font_awesome'),
  path('icons/flag-icon/', views.flag_icon, name='flag_icon'),
  path('icons/material-icon/', views.material_icon, name='material_icon'),
  path('icons/simple-line/', views.simple_line, name='simple_line'),
  path('icons/themify-icon/', views.themify_icon, name='themify_icon'),

  # Forms Layouts
  path('forms/form-basic/', views.form_basic, name='form_basic'),
  path('forms/form-elements/', views.form_elements, name='form_elements'),
  path('forms/input-group/', views.input_group, name='input_group'),
  path('forms/checkbox/', views.form_checkbox, name='form_checkbox'),
  path('forms/radio/', views.form_radio, name='form_radio'),
  path('forms/switch/', views.form_switch, name='form_switch'),
  path('forms/mega-option/', views.form_megaoption, name='form_megaoption'),

  # Form Plugins
  path('forms/datepicker/', views.form_datepicker, name="form_datepicker"),
  path('forms/date-range-picker/', views.form_date_rangepicker, name="form_date_rangepicker"),
  path('forms/timepicker/', views.form_timepicker, name="form_timepicker"),
  path('forms/choices/', views.form_choices, name="form_choices"),
  path('forms/google-recaptcha/', views.google_recaptcha, name="google_recaptcha"),
  path('forms/input-mask/', views.form_input_mask, name="form_input_mask"),
  path('forms/clipboard/', views.clipboard, name="clipboard"),
  path('forms/nouislider/', views.form_nouislider, name="form_nouislider"),
  path('forms/bootstrap-switch/', views.bs_form_switch, name="bs_form_switch"),
  path('forms/typeahead/', views.typeahead, name="typeahead"),

  # Text Editors
  path('forms/tinymce/', views.tinymce, name="tinymce"),
  path('forms/quill/', views.quill, name="quill"),
  path('forms/classic-editor/', views.classic_editor, name="classic_editor"),
  path('forms/document-editor/', views.document_editor, name="document_editor"),
  path('forms/inline-editor/', views.inline_editor, name="inline_editor"),
  path('forms/balloon-editor/', views.balloon_editor, name="balloon_editor"),
  path('forms/bootstrap-markdown/', views.bs_markdown, name="bs_markdown"),

  # Form Layouts
  path('forms/default-layout/', views.default_layout, name="default_layout"),
  path('forms/multicolumn-layout/', views.multicolumn_layout, name="multicolumn_layout"),
  path('forms/actionbars-layout/', views.actionbars_layout, name="actionbars_layout"),
  path('forms/sticky-actionbars-layout/', views.sticky_actionbars_layout, name="sticky_actionbars_layout"),

  # File Upload
  path('forms/dropzone/', views.dropzone, name="dropzone"),
  path('forms/uppy/', views.uppy, name="uppy"),

  path('form/validation/', views.form_validation, name="form_validation"),
  path('form/image-cropper/', views.image_cropper, name="image_cropper"),

  # Table
  path('table/bs-table/', views.bs_table, name="bs_table"),

  # Vanilla Table
  path('tables/basic-table/', views.basic_table, name="basic_table"),
  path('tables/dynamic-import/', views.dynamic_import, name="dynamic_import"),
  path('tables/render-column-cells/', views.render_column_cells, name="render_column_cells"),
  path('tables/column-manipulation/', views.column_manipulation, name="column_manipulation"),
  path('tables/datetime-sorting/', views.datetime_sorting, name="datetime_sorting"),
  path('tables/methods/', views.methods, name="methods"),
  path('tables/add-rows/', views.add_rows, name="add_rows"),
  path('tables/fetch-api/', views.fetch_api, name="fetch_api"),
  path('tables/filters/', views.filters, name="filters"),
  path('tables/export/', views.export, name="export"),

  # Data Table
  path('data-tables/basic-table/', views.dt_basic_table, name="dt_basic_table"),
  path('data-tables/advance-table/', views.dt_advance_table, name="dt_advance_table"),
  path('data-tables/styling-table/', views.dt_styling, name="dt_styling"),
  path('data-tables/api-initialization/', views.dt_api, name="dt_api"),
  path('data-tables/plugin-initialization/', views.dt_plugin, name="dt_plugin"),
  path('data-tables/data-sources/', views.dt_data_source, name="dt_data_source"),
  path('data-tables/data-sources/', views.dt_data_source, name="dt_data_source"),

  # DT Extensions
  path('data-tables/autofill/', views.dt_autofill, name="dt_autofill"),
  path('data-tables/basic-button/', views.dt_basic_button, name="dt_basic_button"),
  path('data-tables/data-export/', views.dt_data_export, name="dt_data_export"),
  path('data-tables/column-reorder/', views.dt_col_reorder, name="dt_col_reorder"),
  path('data-tables/fixed-column/', views.dt_fixed_columns, name="dt_fixed_columns"),
  path('data-tables/fixed-header/', views.dt_fixed_header, name="dt_fixed_header"),
  path('data-tables/key-table/', views.dt_key_table, name="dt_key_table"),
  path('data-tables/responsive/', views.dt_responsive, name="dt_responsive"),
  path('data-tables/row-reorder/', views.dt_row_reorder, name="dt_row_reorder"),
  path('data-tables/scroller/', views.dt_scroller, name="dt_scroller"),
  path('data-tables/select-table/', views.dt_select_table, name="dt_select_table"),

  # Charts
  path('charts/amchart-4/', views.amchart_4, name="amchart_4"),
  path('charts/chartjs/', views.chartjs, name="chartjs"),
  path('charts/google-chart/', views.chart_google, name="chart_google"),
  path('charts/highchart/', views.chart_highchart, name="chart_highchart"),
  path('charts/radial/', views.chart_radial, name="chart_radial"),

  # Maps

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("", views.order_list, name="order_list"),
    path("create/", views.order_create, name="order_create"),
    path("<int:pk>/", views.order_detail, name="order_detail"),
    path("<int:pk>/edit/", views.order_edit, name="order_edit"),
    path("<int:pk>/delete/", views.order_delete, name="order_delete"),
    path("<int:pk>/process/", views.process_order, name="process_order"),
    path("purchase-orders/", views.purchase_order_list, name="purchase_order_list"),
    path(
        "purchase-orders/<int:po_id>/download/",
        views.download_purchase_order,
        name="download_po",
    ),
    path(
        "generate-po/<int:order_id>/<int:supplier_id>/",
        views.generate_purchase_order,
        name="generate_po",
    ),
    path("save-item/<int:item_id>/", views.save_order_item, name="save_order_item"),
    path(
        "purchase-orders/preview/<int:po_id>/",
        views.preview_purchase_order,
        name="preview_po",
    ),
    path(
        "purchase-orders/<int:po_id>/email/",
        views.email_purchase_order,
        name="email_po",
    ),
    path("split-item/<int:item_id>/", views.split_order_item, name="split_order_item"),
    path("create/{mailto_url}", views.handle_mailto_error, name="handle_mailto_error"),
    path("create/{mailto_url}", views.handle_mailto_error, name="mailto_error"),
    path("create/<path:path>", views.handle_mailto_error, name="catchall_error"),
    path(
        "api/check-po-items/<int:order_id>/",
        views.check_po_items,
        name="check_po_items",
    ),
    path("check-order-number/", views.check_order_number, name="check_order_number"),
    path(
        "find-matching-quotes/<int:pk>/",
        views.find_matching_quotes,
        name="find_matching_quotes",
    ),
    path(
        "link-quote/<int:order_id>/<int:quote_id>/", views.link_quote, name="link_quote"
    ),
    path("unlink-quote/<int:order_id>/", views.unlink_quote, name="unlink_quote"),
    path("batch-match-quotes/", views.batch_match_quotes, name="batch_match_quotes"),
    path("reset-matching/", views.reset_matching, name="reset_matching"),
    path(
        "reset-selected-matching/",
        views.reset_selected_matching,
        name="reset_selected_matching",
    ),
    path("check-duplicates/", views.check_duplicates, name="check_duplicates"),
    path(
        "reset-order-matching/<int:pk>/",
        views.reset_order_matching,
        name="reset_order_matching",
    ),
    path(
        "reset-order-matching/<int:pk>/",
        views.reset_order_matching,
        name="reset_order_matching",
    ),
    path("items/", views.order_item_list, name="order_item_list"),
    path("optimized/", views.order_list_optimized, name="order_list_optimized"),
]

wfdash/urls.py
from django.urls import path, include
from . import views
from . import api  # Make sure this import exists

app_name = "wfdash"

urlpatterns = [
    path("", views.index, name="index"),
    # Customer URLs
    path("customers/", views.customers, name="customers"),
    path("customers/list/", views.customers_list, name="customers_list"),
    path("customer/edit/<int:pk>/", views.customer_edit, name="customer_edit"),
    path("customer/delete/<int:pk>/", views.customer_delete, name="customer_delete"),
    # Supplier URLs
    path("suppliers/", views.suppliers, name="suppliers"),
    path("suppliers/list/", views.suppliers_list, name="suppliers_list"),
    path("supplier/edit/<int:pk>/", views.supplier_edit, name="supplier_edit"),
    path("supplier/delete/<int:pk>/", views.supplier_delete, name="supplier_delete"),
    # Company URLs
    path("company/", views.company, name="company"),
    path("company/list/", views.company_list, name="company_list"),
    path("company/edit/<int:pk>/", views.company_edit, name="company_edit"),
    path("company/delete/<int:pk>/", views.company_delete, name="company_delete"),
    # API endpoints
    path("api/company/search/", views.company_search, name="api_company_search"),
    path("api/supplier-search/", views.supplier_search, name="api_supplier_search"),
    path("supplier_search/", views.supplier_search, name="supplier_search"),
    path("api/companies/search/", api.company_search, name="company_search"),
    path(
        "supplier-search/", views.supplier_search, name="supplier_search"
    ),  # Add this alternative URL
    # Universal search
    path("search/", views.universal_search, name="universal_search"),
    # Orders app URLs
    path("orders/", include("orders.urls", namespace="orders")),
    # Additional URL
    path(
        "get_company_address/<int:company_id>/",
        views.get_company_address,
        name="get_company_address",
    ),
    # Recent customers URL
    path("recent_customers/", views.recent_customers, name="recent_customers"),
]

templates/includes/menu_items/buyer_menu.html
<!-- Company Management
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-briefcase"></i></span>
        <span class="pcoded-mtext">Company Management</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'wfdash:company' %}"><i class="feather icon-plus me-2"></i>Add Company</a></li>
        <li><a href="{% url 'wfdash:company_list' %}"><i class="feather icon-list me-2"></i>Companies List</a></li>
    </ul>
</li> -->

<!-- Customer Management 
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-users"></i></span>
        <span class="pcoded-mtext">Customers</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'wfdash:customers' %}"><i class="feather icon-user-plus me-2"></i>Add Customer</a></li>
        <li><a href="{% url 'wfdash:customers_list' %}"><i class="feather icon-list me-2"></i>Customer List</a></li>
    </ul>
</li>-->

<!-- Supplier Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-smartphone"></i></span>
        <span class="pcoded-mtext">Suppliers</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'wfdash:suppliers' %}"><i class="feather icon-plus-square me-2"></i>Add Supplier</a></li>
        <li><a href="{% url 'wfdash:suppliers_list' %}"><i class="feather icon-list me-2"></i>Supplier List</a></li>
    </ul>
</li>

<!-- Quote Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-file-text"></i></span>
        <span class="pcoded-mtext">Quote Management</span>
    </a>
    <ul class="pcoded-submenu">

        <!-- Quote Management 
        <li><a href="{% url 'quotes:quote_create' %}"><i class="feather icon-plus-circle me-2"></i>New Quote</a></li>
        -->
        
        <li><a href="{% url 'quotes:quote_list' %}"><i class="feather icon-list me-2"></i>Quote List</a></li>
        <li><a href="{% url 'quotes:generated_quotes' %}"><i class="feather icon-box me-2"></i>Generated Quotes</a></li>
        <li><a href="{% url 'quotes:archived_quotes' %}"><i class="feather icon-briefcase me-2"></i>Archived Quotes</a></li>
    </ul>
</li>

<!-- Order Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-shopping-cart"></i></span>
        <span class="pcoded-mtext">Order Management</span>
    </a>
    <ul class="pcoded-submenu">

        <li><a href="{% url 'orders:order_create' %}"><i class="feather icon-plus-circle me-2"></i>New Order</a></li>
        <li><a href="{% url 'orders:order_list' %}"><i class="feather icon-list me-2"></i>Order List</a></li>
        <li><a href="{% url 'orders:order_list_optimized' %}"><i class="feather icon-list me-2"></i>Order List_OPTIMIZED</a></li>
        <li><a href="{% url 'orders:purchase_order_list' %}"><i class="feather icon-file-text me-2"></i>Purchase Orders</a></li>
    </ul>
</li>
















<!-- Driver Operations -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-compass"></i></span>
        <span class="pcoded-mtext">Driver Operations</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'driver_list:collection_pool' %}"><i class="feather icon-inbox me-2"></i>Collection Pool</a></li>
        <li><a href="{% url 'driver_list:assigned_collections' %}"><i class="feather icon-check-square me-2"></i>Assigned Collections</a></li>
        <li><a href="{% url 'driver_list:completed_collections' %}"><i class="feather icon-check-circle me-2"></i>Completed Collections</a></li>
    </ul>
</li>

<!-- Stock Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-package"></i></span>
        <span class="pcoded-mtext">Stock Management</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'stock_management:stock_verification' %}"><i class="feather icon-check me-2"></i>Stock Verification</a></li>

<!-- Stock Management 
        <li><a href="{% url 'stock_management:stock_list' %}"><i class="feather icon-list me-2"></i>Current Stock</a></li>
        <li><a href="{% url 'stock_management:ready_to_pick' %}"><i class="feather icon-box me-2"></i>Ready to Pick</a></li>
        <li><a href="{% url 'stock_management:delivery_pick_list' %}"><i class="feather icon-clipboard me-2"></i>Delivery Pick List</a></li>
        <li><a href="{% url 'stock_management:ready_for_delivery' %}"><i class="feather icon-truck me-2"></i>Ready for Delivery</a></li>
        <li><a href="{% url 'stock_management:office_stock' %}"><i class="feather icon-compass me-2"></i>Office Stock</a></li>
-->

    </ul>
</li>

<!-- Reports & Analytics
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-bar-chart-2"></i></span>
        <span class="pcoded-mtext">Reports</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'dashboard:index' %}"><i class="feather icon-pie-chart me-2"></i>Dashboard</a></li>
    </ul>
</li> -->

templates/includes/menu_items/rep_menu.html
<!-- Company Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-briefcase"></i></span>
        <span class="pcoded-mtext">Company Management</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'wfdash:company' %}"><i class="feather icon-plus me-2"></i>Add Company</a></li>
        <li><a href="{% url 'wfdash:company_list' %}"><i class="feather icon-list me-2"></i>Companies List</a></li>
    </ul>
</li>

<!-- Customer Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-users"></i></span>
        <span class="pcoded-mtext">Customers</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'wfdash:customers' %}"><i class="feather icon-user-plus me-2"></i>Add Customer</a></li>
        <li><a href="{% url 'wfdash:customers_list' %}"><i class="feather icon-list me-2"></i>Customer List</a></li>
    </ul>
</li>

<!-- Supplier Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-smartphone"></i></span>
        <span class="pcoded-mtext">Suppliers</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'wfdash:suppliers' %}"><i class="feather icon-plus-square me-2"></i>Add Supplier</a></li>
        <li><a href="{% url 'wfdash:suppliers_list' %}"><i class="feather icon-list me-2"></i>Supplier List</a></li>
    </ul>
</li>

<!-- Quote Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-file-text"></i></span>
        <span class="pcoded-mtext">Quote Management</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'quotes:quote_create' %}"><i class="feather icon-plus-circle me-2"></i>New Quote</a></li>
        <li><a href="{% url 'quotes:quote_list' %}"><i class="feather icon-list me-2"></i>Quote List</a></li>
        <li><a href="{% url 'quotes:pending_approvals' %}"><i class="feather icon-check-circle"></i>Quotes for Approval</a></li>
        <li><a href="{% url 'quotes:generated_quotes' %}"><i class="feather icon-box me-2"></i>Generated Quotes</a></li>
        <li><a href="{% url 'quotes:archived_quotes' %}"><i class="feather icon-briefcase me-2"></i>Archived Quotes</a></li>
    </ul>
</li>

<!-- Order Management -->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-shopping-cart"></i></span>
        <span class="pcoded-mtext">Order Management</span>
    </a>
    <ul class="pcoded-submenu">
 
        <li><a href="{% url 'orders:order_list' %}"><i class="feather icon-list me-2"></i>Order List</a></li>

    </ul>
</li>



<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-file-text"></i></span>
        <span class="pcoded-mtext">Delivery Notes</span>
    </a>
    <ul class="pcoded-submenu">

        <li><a href="{% url 'delivery_notes:create' %}"><i class="feather icon-plus-circle me-2"></i>New Delivery Note</a></li>
        <li><a href="{% url 'delivery_notes:list' %}"><i class="feather icon-list me-2"></i>Delivery Notes List</a></li>
    
    </ul>
</li>




<!-- Reports & Analytics-->
<li class="nav-item pcoded-hasmenu">
    <a href="#!" class="nav-link">
        <span class="pcoded-micon"><i class="feather icon-bar-chart-2"></i></span>
        <span class="pcoded-mtext">Reports</span>
    </a>
    <ul class="pcoded-submenu">
        <li><a href="{% url 'dashboard:rep_dashboard' %}"><i class="feather icon-pie-chart me-2"></i>Rep Dashboard</a></li>
    </ul>
</li>